PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_100000_create_shops_table',1);
INSERT INTO migrations VALUES(4,'0001_01_01_110000_create_branches_table',1);
INSERT INTO migrations VALUES(5,'0001_01_01_200000_create_users_table',1);
INSERT INTO migrations VALUES(6,'2026_03_26_223839_create_products_table',1);
INSERT INTO migrations VALUES(7,'2026_03_26_223914_create_branch_stocks_table',1);
INSERT INTO migrations VALUES(8,'2026_03_26_223937_create_customers_table',1);
INSERT INTO migrations VALUES(9,'2026_03_26_224010_create_sales_table',1);
INSERT INTO migrations VALUES(10,'2026_03_26_224435_create_sale_items_table',1);
INSERT INTO migrations VALUES(11,'2026_03_26_224453_create_payments_table',1);
INSERT INTO migrations VALUES(12,'2026_03_26_224504_create_expenses_table',1);
INSERT INTO migrations VALUES(13,'2026_03_26_224525_create_activity_logs_table',1);
INSERT INTO migrations VALUES(14,'2026_03_27_000000_create_sessions_table',1);
INSERT INTO migrations VALUES(15,'2026_03_30_161557_create_stock_transfers_table',1);
INSERT INTO migrations VALUES(16,'2026_04_05_130012_setings',1);
INSERT INTO migrations VALUES(17,'2026_04_10_105222_create_purchase_orders_table',1);
INSERT INTO migrations VALUES(18,'2026_04_13_113045_create_licenses_table',1);
INSERT INTO migrations VALUES(19,'2026_04_13_120000_create_license_plans_table',1);
INSERT INTO migrations VALUES(20,'2026_04_13_130000_create_license_verifications_table',1);
INSERT INTO migrations VALUES(21,'2026_04_15_135016_create_update_histories_table',1);
INSERT INTO migrations VALUES(22,'2026_04_21_165145_create_tax_rates_table',1);
INSERT INTO migrations VALUES(23,'2026_04_22_181415_add_tax_rate_id_to_shops_table',1);
INSERT INTO migrations VALUES(24,'2026_04_22_181500_add_tax_fields_to_sale_items_table',1);
INSERT INTO migrations VALUES(25,'2026_04_22_181501_add_tax_fields_to_sales_table',1);
INSERT INTO migrations VALUES(26,'2026_04_22_214406_add_order_to_tax_rates_table',1);
INSERT INTO migrations VALUES(27,'2026_04_22_215749_add_tax_breakdown_to_sales_table',1);
INSERT INTO migrations VALUES(28,'2026_04_30_004951_create_peers_table',2);
INSERT INTO migrations VALUES(29,'2026_04_30_004952_create_sync_outbox_table',2);
INSERT INTO migrations VALUES(30,'2026_04_30_010039_create_personal_access_tokens_table',3);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
INSERT INTO cache VALUES('ominipos-cache-local_ip','s:11:"172.31.0.85";',2092873746);
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "branches" ("id" integer primary key autoincrement not null, "shop_id" integer not null, "name" varchar not null, "address" varchar, "phone" varchar, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("shop_id") references "shops"("id") on delete cascade);
INSERT INTO branches VALUES(1,1,'Main Branch','Modi sint accusamus','+1 (752) 908-3925',1,'2026-04-30 01:06:27','2026-04-30 01:06:27');
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "shop_id" integer, "branch_id" integer, "name" varchar not null, "email" varchar not null, "phone" varchar, "role" varchar check ("role" in ('owner', 'admin', 'manager', 'cashier')) not null default 'cashier', "email_verified_at" datetime, "password" varchar not null, "is_active" tinyint(1) not null default '1', "remember_token" varchar, "created_at" datetime, "updated_at" datetime, foreign key("shop_id") references "shops"("id") on delete set null, foreign key("branch_id") references "branches"("id") on delete set null);
INSERT INTO users VALUES(1,1,1,'Graham Ransford','grahamransford3@gmail.com','0542069352','owner',NULL,'$2y$12$K8hSOWqsqZ2pZH58w/8FJOgeLX8/6x2awyI9ZnW4/d.HFkr9mpbn6',1,NULL,'2026-04-30 01:06:29','2026-04-30 01:06:29');
CREATE TABLE IF NOT EXISTS "products" ("id" integer primary key autoincrement not null, "shop_id" integer not null, "name" varchar not null, "barcode" varchar, "sku" varchar, "category" varchar, "description" text, "price" numeric not null default '0', "cost" numeric not null default '0', "unit" varchar not null default 'piece', "image" varchar, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("shop_id") references "shops"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "branch_stocks" ("id" integer primary key autoincrement not null, "branch_id" integer not null, "product_id" integer not null, "quantity" numeric not null default '0', "low_stock_alert" numeric not null default '5', "created_at" datetime, "updated_at" datetime, foreign key("branch_id") references "branches"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "customers" ("id" integer primary key autoincrement not null, "shop_id" integer not null, "name" varchar not null, "phone" varchar, "email" varchar, "address" varchar, "credit_limit" numeric not null default '0', "outstanding_balance" numeric not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("shop_id") references "shops"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "sales" ("id" integer primary key autoincrement not null, "reference" varchar not null, "branch_id" integer not null, "user_id" integer not null, "customer_id" integer, "subtotal" numeric not null default '0', "discount" numeric not null default '0', "tax" numeric not null default '0', "total" numeric not null default '0', "amount_paid" numeric not null default '0', "change" numeric not null default '0', "balance_due" numeric not null default '0', "status" varchar check ("status" in ('completed', 'pending', 'cancelled', 'refunded')) not null default 'completed', "payment_status" varchar check ("payment_status" in ('paid', 'partial', 'unpaid')) not null default 'paid', "notes" text, "created_at" datetime, "updated_at" datetime, "tax_total" numeric not null default '0', "tax_breakdown" text, foreign key("branch_id") references "branches"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade, foreign key("customer_id") references "customers"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "sale_items" ("id" integer primary key autoincrement not null, "sale_id" integer not null, "product_id" integer not null, "product_name" varchar not null, "price" numeric not null, "cost" numeric not null default '0', "quantity" numeric not null, "discount" numeric not null default '0', "total" numeric not null, "is_returned" tinyint(1) not null default '0', "returned_quantity" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "tax_rate" numeric not null default '0', "tax_amount" numeric not null default '0', foreign key("sale_id") references "sales"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "payments" ("id" integer primary key autoincrement not null, "sale_id" integer not null, "customer_id" integer, "method" varchar check ("method" in ('cash', 'mobile_money', 'card', 'credit')) not null default 'cash', "receipt_number" varchar, "amount" numeric not null, "reference" varchar, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("sale_id") references "sales"("id") on delete cascade, foreign key("customer_id") references "customers"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "expenses" ("id" integer primary key autoincrement not null, "branch_id" integer not null, "user_id" integer not null, "title" varchar not null, "category" varchar not null default 'general', "amount" numeric not null, "notes" text, "expense_date" date not null, "created_at" datetime, "updated_at" datetime, foreign key("branch_id") references "branches"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "activity_logs" ("id" integer primary key autoincrement not null, "user_id" integer, "branch_id" integer, "action" varchar not null, "model_type" varchar, "model_id" integer, "data" text, "ip_address" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete set null, foreign key("branch_id") references "branches"("id") on delete set null);
INSERT INTO activity_logs VALUES(1,1,1,'logout',NULL,NULL,'[]','127.0.0.1','2026-04-30 02:06:14','2026-04-30 02:06:14');
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
INSERT INTO sessions VALUES('bBG0SoO1zUdKHzRf2k7m1BM26vduczoeOzdbBNyk',NULL,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36 Edg/147.0.0.0','eyJfdG9rZW4iOiJHaFJGd1B5TUgyZFVRU1J4WWQydlhQQmp4M240MHliODBIRmMybzBLIiwiX2ZsYXNoIjp7Im9sZCI6W10sIm5ldyI6W119LCJfcHJldmlvdXMiOnsidXJsIjoiaHR0cHM6XC9cL3Nob3Bwb3MudGVzdFwvc2V0dXBcL2NoZWNrIiwicm91dGUiOiJzZXR1cC5jaGVjayJ9fQ==',1777514774);
CREATE TABLE IF NOT EXISTS "stock_transfers" ("id" integer primary key autoincrement not null, "product_id" integer not null, "from_branch_id" integer not null, "to_branch_id" integer not null, "user_id" integer not null, "quantity" numeric not null, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("product_id") references "products"("id") on delete cascade, foreign key("from_branch_id") references "branches"("id") on delete cascade, foreign key("to_branch_id") references "branches"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "settings" ("id" integer primary key autoincrement not null, "shop_id" integer not null, "branch_id" integer, "key" varchar not null, "value" text, "type" varchar not null default 'string', "created_at" datetime, "updated_at" datetime, foreign key("shop_id") references "shops"("id") on delete cascade, foreign key("branch_id") references "branches"("id") on delete set null);
INSERT INTO settings VALUES(1,1,NULL,'shop_name','Tempore','string','2026-04-30 01:27:31','2026-04-30 01:27:43');
INSERT INTO settings VALUES(2,1,NULL,'shop_phone','+1 (752) 908-3925','string','2026-04-30 01:27:31','2026-04-30 01:27:31');
INSERT INTO settings VALUES(3,1,NULL,'shop_address','Modi sint accusamus','string','2026-04-30 01:27:31','2026-04-30 01:27:31');
INSERT INTO settings VALUES(4,1,NULL,'shop_email','v@mailinator.com','string','2026-04-30 01:27:31','2026-04-30 01:27:43');
INSERT INTO settings VALUES(5,1,NULL,'currency','Incididunt','string','2026-04-30 01:27:31','2026-04-30 01:27:31');
INSERT INTO settings VALUES(6,1,NULL,'currency_symbol','Nemo','string','2026-04-30 01:27:31','2026-04-30 01:27:31');
INSERT INTO settings VALUES(7,1,NULL,'default_tax_rate_id','1','string','2026-04-30 01:27:31','2026-04-30 02:05:12');
INSERT INTO settings VALUES(8,1,1,'mail_gmail_address','grahamransford3@gmail.com','string','2026-04-30 01:28:21','2026-04-30 01:28:21');
INSERT INTO settings VALUES(9,1,1,'mail_gmail_app_password','wadadadadad','string','2026-04-30 01:28:21','2026-04-30 01:28:21');
INSERT INTO settings VALUES(10,1,1,'mail_from_name','Main Branch','string','2026-04-30 01:28:21','2026-04-30 01:28:21');
INSERT INTO settings VALUES(11,1,1,'mail_enabled','1','boolean','2026-04-30 01:28:21','2026-04-30 01:28:21');
INSERT INTO settings VALUES(12,1,NULL,'notify_low_stock','1','boolean','2026-04-30 01:28:28','2026-04-30 01:28:28');
INSERT INTO settings VALUES(13,1,NULL,'notify_new_sale','1','boolean','2026-04-30 01:28:28','2026-04-30 01:28:28');
INSERT INTO settings VALUES(14,1,NULL,'notify_daily_summary','1','boolean','2026-04-30 01:28:28','2026-04-30 01:28:28');
INSERT INTO settings VALUES(15,1,NULL,'notify_debt_reminder','1','boolean','2026-04-30 01:28:28','2026-04-30 01:28:28');
CREATE TABLE IF NOT EXISTS "purchase_orders" ("id" integer primary key autoincrement not null, "reference" varchar not null, "shop_id" integer not null, "branch_id" integer not null, "created_by" integer not null, "approved_by" integer, "supplier_name" varchar, "supplier_phone" varchar, "notes" text, "status" varchar check ("status" in ('draft', 'pending', 'approved', 'rejected', 'partial', 'received')) not null default 'draft', "approved_at" datetime, "expected_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("shop_id") references "shops"("id") on delete cascade, foreign key("branch_id") references "branches"("id") on delete cascade, foreign key("created_by") references "users"("id") on delete cascade, foreign key("approved_by") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "purchase_order_items" ("id" integer primary key autoincrement not null, "purchase_order_id" integer not null, "product_id" integer not null, "product_name" varchar not null, "quantity_requested" numeric not null, "quantity_received" numeric not null default '0', "unit_cost" numeric not null default '0', "status" varchar check ("status" in ('pending', 'received', 'partial', 'missing')) not null default 'pending', "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("purchase_order_id") references "purchase_orders"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "licenses" ("id" integer primary key autoincrement not null, "license_key" varchar not null, "plan_name" varchar, "plan_slug" varchar, "status" varchar check ("status" in ('active', 'expired', 'invalid', 'suspended')) not null default 'active', "activated_at" datetime, "expires_at" datetime, "verified_at" datetime, "verification_token" varchar, "days_remaining" integer not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "license_plans" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "duration_days" integer not null, "price" numeric not null, "currency" varchar not null default 'GHS', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "license_verifications" ("id" integer primary key autoincrement not null, "license_id" integer not null, "ip_address" varchar, "domain" varchar, "success" tinyint(1) not null default '0', "verified_at" datetime not null, "created_at" datetime, "updated_at" datetime, foreign key("license_id") references "licenses"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "update_histories" ("id" integer primary key autoincrement not null, "version_checked" varchar not null, "new_version" varchar, "status" varchar not null, "message" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "tax_rates" ("id" integer primary key autoincrement not null, "name" varchar not null, "rate" numeric not null, "description" text, "is_active" tinyint(1) not null default '1', "created_by" integer, "created_at" datetime, "updated_at" datetime, "order" integer not null default '0', foreign key("created_by") references "users"("id") on delete set null);
INSERT INTO tax_rates VALUES(1,'Similique reprehende',1,'Ea autem et esse am',1,1,'2026-04-30 01:28:01','2026-04-30 01:28:01',0);
CREATE TABLE IF NOT EXISTS "shops" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "email" varchar, "phone" varchar, "address" varchar, "logo" varchar, "currency" varchar not null default ('GHS'), "currency_symbol" varchar not null default ('₵'), "is_active" tinyint(1) not null default ('1'), "created_at" datetime, "updated_at" datetime, "default_tax_rate_id" integer, foreign key("default_tax_rate_id") references "tax_rates"("id") on delete set null);
INSERT INTO shops VALUES(1,'Tempore','tempore-consequuntu-Y3ON','v@mailinator.com','+1 (752) 908-3925','Modi sint accusamus',NULL,'Incididunt','Nemo',1,'2026-04-30 01:06:27','2026-04-30 02:05:12',1);
CREATE TABLE IF NOT EXISTS "peers" ("id" integer primary key autoincrement not null, "name" varchar, "ip_address" varchar not null, "is_active" tinyint(1) not null default '1', "last_seen" datetime, "created_at" datetime, "updated_at" datetime);
INSERT INTO peers VALUES(4,'PC2','192.168.1.2',1,'2026-04-30 09:06:13','2026-04-30 01:46:11','2026-04-30 09:06:13');
CREATE TABLE IF NOT EXISTS "sync_outbox" ("id" integer primary key autoincrement not null, "table_name" varchar not null, "record_id" integer not null, "action" varchar check ("action" in ('create', 'update', 'delete')) not null, "data" text, "synced" tinyint(1) not null default '0', "created_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" text not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
INSERT INTO sqlite_sequence VALUES('migrations',30);
INSERT INTO sqlite_sequence VALUES('shops',1);
INSERT INTO sqlite_sequence VALUES('branches',1);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('settings',15);
INSERT INTO sqlite_sequence VALUES('tax_rates',1);
INSERT INTO sqlite_sequence VALUES('peers',4);
INSERT INTO sqlite_sequence VALUES('activity_logs',1);
CREATE INDEX "cache_expiration_index" on "cache" ("expiration");
CREATE INDEX "cache_locks_expiration_index" on "cache_locks" ("expiration");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "products_barcode_index" on "products" ("barcode");
CREATE UNIQUE INDEX "branch_stocks_branch_id_product_id_unique" on "branch_stocks" ("branch_id", "product_id");
CREATE UNIQUE INDEX "sales_reference_unique" on "sales" ("reference");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE UNIQUE INDEX "settings_shop_id_branch_id_key_unique" on "settings" ("shop_id", "branch_id", "key");
CREATE UNIQUE INDEX "purchase_orders_reference_unique" on "purchase_orders" ("reference");
CREATE UNIQUE INDEX "licenses_license_key_unique" on "licenses" ("license_key");
CREATE UNIQUE INDEX "license_plans_slug_unique" on "license_plans" ("slug");
CREATE UNIQUE INDEX "shops_slug_unique" on "shops" ("slug");
CREATE INDEX "sync_outbox_table_name_record_id_synced_index" on "sync_outbox" ("table_name", "record_id", "synced");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE INDEX "personal_access_tokens_expires_at_index" on "personal_access_tokens" ("expires_at");
COMMIT;
